using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core;

public struct AgentSaveData(string characterStringId, MatrixFrame spawnFrame, string[] agentSpawnPointTags, int agentSeed)
{
	[SaveableField(1)]
	public readonly string CharacterStringId = characterStringId;

	[SaveableField(2)]
	public MatrixFrame SpawnFrame = spawnFrame;

	[SaveableField(3)]
	public readonly string[] AgentSpawnPointTags = agentSpawnPointTags;

	[SaveableField(4)]
	public readonly int AgentSeed = agentSeed;

	public void UpdateSpawnFrame(MatrixFrame spawnFrame)
	{
		SpawnFrame = spawnFrame;
	}

	public static void AutoGeneratedStaticCollectObjectsAgentSaveData(object o, List<object> collectedObjects)
	{
		((AgentSaveData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(AgentSpawnPointTags);
	}

	internal static object AutoGeneratedGetMemberValueCharacterStringId(object o)
	{
		return ((AgentSaveData)o).CharacterStringId;
	}

	internal static object AutoGeneratedGetMemberValueSpawnFrame(object o)
	{
		return ((AgentSaveData)o).SpawnFrame;
	}

	internal static object AutoGeneratedGetMemberValueAgentSpawnPointTags(object o)
	{
		return ((AgentSaveData)o).AgentSpawnPointTags;
	}

	internal static object AutoGeneratedGetMemberValueAgentSeed(object o)
	{
		return ((AgentSaveData)o).AgentSeed;
	}
}
